---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.0-develop
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /appdata/sonarr:/config
      - /share_media:/data
    ports:
      - 8989:8989
    networks:
      - htpc
    restart: unless-stopped
    
networks:
  htpc:
    external: true
