---
version: "2.1"
services:
  qbittorrent:
    # latest version seems to memory leak and use tons of RAM with no limits in sight
    image: lscr.io/linuxserver/qbittorrent:14.3.9
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - WEBUI_PORT=8082
    volumes:
      - /appdata/qbittorrent:/config
      - /share_media:/data
    restart: unless-stopped
