---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - /appdata/radarr:/config
      - /share_media:/data
    ports:
      - 7878:7878
    networks:
      - htpc  
    restart: unless-stopped
    
networks:
  htpc:
    external: true