version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /appdata/nginx:/data
      - /appdata/letsencrypt:/etc/letsencrypt

    networks:
      htpc:
        ipv4_address: 172.18.0.3
    restart: unless-stopped

networks:
  htpc:
    external: true